version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: bash .circleci/setup-heroku.sh
     - run: |         
         docker login --username=$ultwolf@gmail.com --password=e44ae292-5cd8-41e5-aae8-b594f50fb886 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/homeofimage/web
         docker push registry.heroku.com/homeofimage/web       
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku login -i
         heroku container:release web -a homeofimage